apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-standalone-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mysql-standalone"
  claimRef:
    namespace: mysql-operator-system
    name: mysql-sample-pvc
