apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sample-pv
  labels:
    app: mysql-sample
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/mysql-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master-slave-master-pv
  labels:
    app: mysql-master-slave
    component: master
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  hostPath:
    path: /tmp/mysql-master-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master-slave-slave-0-pv
  labels:
    app: mysql-master-slave
    component: slave
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  hostPath:
    path: /tmp/mysql-slave-0-data