---
# Main tasks file for MySQL Operator

- name: Set variables from spec
  set_fact:
    deployment_mode: "{{ mode | default(mysql_mode) }}"
    image: "{{ image | default(mysql_image) }}"
    root_password: "{{ rootPassword | default(mysql_root_password) }}"
    database: "{{ database | default(mysql_database) }}"
    storage_size: "{{ storage.size | default(mysql_storage_size) }}"
    storage_class: "{{ storage.storageClass | default(mysql_storage_class) }}"
    memory_request: "{{ resources.requests.memory | default(mysql_memory_request) }}"
    cpu_request: "{{ resources.requests.cpu | default(mysql_cpu_request) }}"
    memory_limit: "{{ resources.limits.memory | default(mysql_memory_limit) }}"
    cpu_limit: "{{ resources.limits.cpu | default(mysql_cpu_limit) }}"
    replication_user: "{{ replication.user | default(mysql_replication_user) }}"
    replication_password: "{{ replication.password | default(mysql_replication_password) }}"
    slave_replicas: "{{ replication.slaveReplicas | default(mysql_slave_replicas) }}"

- name: Debug deployment information
  debug:
    msg:
      - "Deployment Mode: {{ deployment_mode }}"
      - "Image         : {{ image }}"
      - "Database      : {{ database }}"
      - "Storage       : {{ storage_size }}"
      - "Namespace     : {{ ansible_operator_meta.namespace }}"
      - "Slave Replicas: {{ slave_replicas if deployment_mode == 'master-slave' else 'N/A' }}"

# Include tasks based on deployment mode
- name: Deploy standalone MySQL
  include_tasks: standalone.yml
  when: deployment_mode == "standalone"

- name: Deploy master-slave MySQL
  include_tasks: master_slave.yml
  when: deployment_mode == "master-slave"

