---
# Main tasks file for MySQL Operator

- name: Debug deployment information
  debug:
    msg:
      - "Deployment Mode: {{ mode | default('standalone') }}"
      - "Image         : {{ image | default('mysql:8.0') }}"
      - "Database      : {{ database | default('') }}"
      - "Root Password : [HIDDEN]"
      - "Namespace     : {{ ansible_operator_meta.namespace }}"
      - "Slave Replicas: {{ replication.slave_replicas | default(1) if mode == 'master-slave' else 'N/A' }}"

# Include tasks based on deployment mode
- name: Deploy standalone MySQL
  include_tasks: standalone.yml
  when: mode | default('standalone') == "standalone"

- name: Deploy master-slave MySQL
  include_tasks: master_slave.yml
  when: mode | default('standalone') == "master-slave"

# Configure replication after master-slave deployment
- name: Configure MySQL replication
  include_tasks: configure_replication.yml
  when: mode | default('standalone') == "master-slave"

# Handle operations
- name: Execute failover operation
  include_tasks: failover.yml
  when: operations.failover.enabled | default(false) and mode == "master-slave"

- name: Configure backup and restore
  include_tasks: backup.yml
  when: operations.backup.enabled | default(false) or operations.restore.enabled | default(false)

# Always setup monitoring for production readiness
- name: Setup monitoring and health checks
  include_tasks: monitoring.yml

