---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - database.qwzhou.local
  resources:
  - mysqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.qwzhou.local
  resources:
  - mysqlclusters/finalizers
  verbs:
  - update
- apiGroups:
  - database.qwzhou.local
  resources:
  - mysqlclusters/status
  verbs:
  - get
  - patch
  - update
