# This rule is not used by the project mysql-operator-ansible itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mysql.qwzhou.local.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-operator-ansible
    app.kubernetes.io/managed-by: kustomize
  name: mysql-admin-role
rules:
- apiGroups:
  - mysql.qwzhou.local
  resources:
  - mysqls
  verbs:
  - '*'
- apiGroups:
  - mysql.qwzhou.local
  resources:
  - mysqls/status
  verbs:
  - get
