apiVersion: mysql.qwzhou.local/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
  namespace: default
spec:
  # MySQL Docker镜像版本 - 支持选择不同版本
  image: "mysql:8.0"
  # MySQL root用户密码 - 必需字段
  rootPassword: "Root@1234!"
  # 初始数据库名称（可选）
  database: "qwzhou_8"
  # 存储配置
  storage:
    size: "20Gi"
    # storageClass: "fast-ssd"  # 可选：指定存储类
  # 资源配置
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
