apiVersion: mysql.qwzhou.local/v1alpha1
kind: MySQL
metadata:
  name: mysql-master-slave
  namespace: qwzhou-mysql-trae
spec:
  # 部署模式：主从架构
  mode: "master-slave"
  # MySQL Docker镜像版本
  image: "crpi-oedkuzepm53hblsq.cn-shanghai.personal.cr.aliyuncs.com/qwzhou_test/mysql:8.0"
  # MySQL root用户密码
  rootPassword: "Root@1234!"
  # 初始数据库名称（可选）
  database: "qwzhou_master_slave"
  # 主从复制配置
  replication:
    user: "replicator"
    password: "Repl@1234!"
    slaveReplicas: 2
  # 存储配置
  storage:
    size: "20Gi"
    # storageClass: "fast-ssd"  # 可选：指定存储类
  # 资源配置
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"