apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/mysql-local
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rk9-k8s-worker1
          - rk9-k8s-worker2
          - rk9-k8s-worker3
          - rk9-k8s-worker4
          - rk9-k8s-worker5
          - rk9-k8s-worker6
  volumeMode: Filesystem