apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sample-pv-clean
  labels:
    app: mysql-sample
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/mysql-sample-clean