apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sample-pv-fresh
  labels:
    app: mysql-sample
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: mysql-sample-pvc
  hostPath:
    path: /tmp/mysql-sample-data-fresh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sample-pvc
  namespace: default
  labels:
    app: mysql-sample
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: mysql-sample