apiVersion: mysql.qwzhou.local/v1alpha1
kind: MySQL
metadata:
  name: test-mysql
  namespace: default
spec:
  mode: "master-slave"
  image: "mysql:8.0"
  rootPassword: "Root@1234!"
  database: "testdb"
  replication:
    user: "replicator"
    password: "Repl@1234!"
    slaveReplicas: 1
  storage:
    size: "10Gi"
    storageClass: ""
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"