apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"mysql-operator-ansible","control-plane":"controller-manager"},"name":"mysql-operator-ansible-controller-manager","namespace":"mysql-operator-ansible-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/name":"mysql-operator-ansible","control-plane":"controller-manager"}},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/default-container":"manager"},"labels":{"app.kubernetes.io/name":"mysql-operator-ansible","control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--metrics-require-rbac","--metrics-secure","--metrics-bind-address=:8443","--leader-elect","--leader-election-id=mysql-operator-ansible","--health-probe-bind-address=:6789"],"env":[{"name":"ANSIBLE_GATHERING","value":"explicit"}],"image":"crpi-oedkuzepm53hblsq.cn-shanghai.personal.cr.aliyuncs.com/qwzhou_test/operator:ansible-20250623135802","livenessProbe":{"httpGet":{"path":"/healthz","port":6789},"initialDelaySeconds":15,"periodSeconds":20},"name":"manager","ports":[],"readinessProbe":{"httpGet":{"path":"/readyz","port":6789},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"768Mi"},"requests":{"cpu":"10m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}},"volumeMounts":[]}],"imagePullSecrets":[{"name":"aliyun-acr-secret"}],"securityContext":{"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"mysql-operator-ansible-controller-manager","terminationGracePeriodSeconds":10,"volumes":[]}}}}
  creationTimestamp: "2025-06-23T03:26:17Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mysql-operator-ansible
    control-plane: controller-manager
  name: mysql-operator-ansible-controller-manager
  namespace: mysql-operator-ansible-system
  resourceVersion: "15125153"
  uid: d86c5ab9-15fc-4cb8-b1b1-943db78d892e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-operator-ansible
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        kubectl.kubernetes.io/restartedAt: "2025-06-23T13:51:45+08:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: mysql-operator-ansible
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-require-rbac
        - --metrics-secure
        - --metrics-bind-address=:8443
        - --leader-elect
        - --leader-election-id=mysql-operator-ansible
        - --health-probe-bind-address=:6789
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        image: crpi-oedkuzepm53hblsq.cn-shanghai.personal.cr.aliyuncs.com/qwzhou_test/operator:ansible-20250623135802
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 10m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aliyun-acr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mysql-operator-ansible-controller-manager
      serviceAccountName: mysql-operator-ansible-controller-manager
      terminationGracePeriodSeconds: 10
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-23T05:52:11Z"
    lastUpdateTime: "2025-06-23T05:52:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-23T05:42:56Z"
    lastUpdateTime: "2025-06-23T05:52:11Z"
    message: ReplicaSet "mysql-operator-ansible-controller-manager-869d854659" has
      successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
