generatorOptions:
  disableNameSuffixHash: true
resources:
- manager.yaml
images:
- name: controller
  newName: crpi-oedkuzepm53hblsq.cn-shanghai.personal.cr.aliyuncs.com/qwzhou_test/operator
  newTag: ansible-20250626175037
patchesStrategicMerge:
- pull-secret-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
