generatorOptions:
  disableNameSuffixHash: true
resources:
- manager.yaml
images:
- name: controller
  newName: controller
  newTag: latest
patchesStrategicMerge:
- pull-secret-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
